// User
export const GET_USER = 'GET_USER';
export const USER_STATUS = 'USER_STATUS';
export const GOOGLE_LOGIN = 'GOOGLE_LOGIN';
export const TWITTER_LOGIN = 'TWITTER_LOGIN';
export const CREATE_ACCOUNT = 'CREATE_ACCOUNT';
export const LOGOUT = 'LOGOUT';
export const LOGIN = 'LOGIN';
export const CREATE_USER = 'CREATE_USER';

// Teacher not assigned
export const FETCH_TEACHERS_NOT_ASSIGNED = 'FETCH_TEACHERS_NOT_ASSIGNED';
export const TEACHER_NOT_ASSIGNED_STATUS = 'TEACHER_NOT_ASSIGNED_STATUS';

// Teacher
export const FETCH_TEACHERS = 'FETCH_TEACHERS';
export const TEACHER_STATUS = 'TEACHER_STATUS';
export const CREATE_TEACHER = 'CREATE_TEACHER';
export const SAVE_TEACHER = 'SAVE_TEACHER';
export const DELETE_TEACHER = 'DELETE_TEACHER';
export const MOVE_TEACHER_TO_CLASSROOM = 'MOVE_TEACHER_TO_CLASSROOM';

// Classroom
export const FETCH_CLASSROOMS = 'FETCH_CLASSROOMS';
export const CLASSROOM_STATUS = 'CLASSROOM_STATUS';
export const CREATE_CLASSROOM = 'CREATE_CLASSROOM';
export const SAVE_CLASSROOM = 'SAVE_CLASSROOM';
export const DELETE_CLASSROOM = 'DELETE_CLASSROOM';