const PENDING = '_PENDING';
const FULFILLED = '_FULFILLED';
const REJECTED = '_REJECTED';

// User
export const GET_USER = 'GET_USER';
export const USER_STATUS = 'USER_STATUS';
export const GOOGLE_LOGIN = 'GOOGLE_LOGIN';
export const GOOGLE_LOGIN_PENDING = GOOGLE_LOGIN + PENDING;
export const GOOGLE_LOGIN_FULFILLED = GOOGLE_LOGIN + FULFILLED;
export const GOOGLE_LOGIN_REJECTED = GOOGLE_LOGIN + REJECTED;
export const CREATE_ACCOUNT = 'CREATE_ACCOUNT';
export const LOGOUT = 'LOGOUT';
export const LOGOUT_PENDING = LOGOUT + PENDING;
export const LOGOUT_FULFILLED = LOGOUT + FULFILLED;
export const LOGOUT_REJECTED = LOGOUT + REJECTED;
export const LOGIN = 'LOGIN';
export const CREATE_USER = 'CREATE_USER';

// Teacher not assigned
export const FETCH_TEACHERS_NOT_ASSIGNED = 'FETCH_TEACHERS_NOT_ASSIGNED';
export const TEACHER_NOT_ASSIGNED_STATUS = 'TEACHER_NOT_ASSIGNED_STATUS';

// Teacher
export const FETCH_TEACHERS = 'FETCH_TEACHERS';
export const TEACHER_STATUS = 'TEACHER_STATUS';
export const CREATE_TEACHER = 'CREATE_TEACHER';
export const SAVE_TEACHER = 'SAVE_TEACHER';
export const DELETE_TEACHER = 'DELETE_TEACHER';
export const MOVE_TEACHER_TO_CLASSROOM = 'MOVE_TEACHER_TO_CLASSROOM';

// Classroom
export const FETCH_CLASSROOMS = 'FETCH_CLASSROOMS';
export const CLASSROOM_STATUS = 'CLASSROOM_STATUS';
export const CREATE_CLASSROOM = 'CREATE_CLASSROOM';
export const SAVE_CLASSROOM = 'SAVE_CLASSROOM';
export const DELETE_CLASSROOM = 'DELETE_CLASSROOM';

// Students
export const FETCH_STUDENTS = 'FETCH_STUDENTS';
export const STUDENT_STATUS = 'STUDENT_STATUS';
export const CREATE_STUDENT = 'CREATE_STUDENT';
export const SAVE_STUDENT = 'SAVE_STUDENT';
export const SAVE_STUDENT_PENDING = SAVE_STUDENT + PENDING;
export const SAVE_STUDENT_FULFILLED = SAVE_STUDENT + FULFILLED;
export const SAVE_STUDENT_REJECTED = SAVE_STUDENT + REJECTED;
export const DELETE_STUDENT = 'DELETE_STUDENT';
export const FETCH_STUDENT = 'FETCH_STUDENT';
export const FETCH_STUDENT_PENDING = FETCH_STUDENT + PENDING;
export const FETCH_STUDENT_FULFILLED = FETCH_STUDENT + FULFILLED;
export const FETCH_STUDENT_REJECTED = FETCH_STUDENT + REJECTED;
